---
title: "Doug and Ronnie's Really Cool Refuge Survey Report"
params:
  input_dat: NA
  dat: NA
  zone: NA
---

## `r unique(dat()$RegionName)` Region
## `r Sys.Date()`


### Input Parameters

This report was generated based on the following filters:

```{r, echo=FALSE}
library(kableExtra)

dat_input_params <- data.frame(parameters = c("Zone",
                                              "Selected survey",
                                              "Search terms",
                                              "Survey Status",
                                              "Refuges",
                                              "Survey type",
                                              "Cooperative survey",
                                              "Resource theme",
                                              "Frequency"),
                               value = c(paste(unique(dat()$Zone), collapse = ", "),
                                         paste(unique(dat()$Selected), collapse = ", "),
                                         paste(input$search, collapse = ", "),
                                         paste(unique(dat()$SurveyStatus), collapse = ", "),
                                         paste(unique(dat()$StationName), collapse = ", "),
                                         paste(unique(dat()$SurveyTypeShort), collapse = ", "),
                                         paste(unique(dat()$Coop), collapse = ", "),
                                         paste(unique(dat()$ResourceThemeLevel2), collapse = ", "),
                                         paste(unique(dat()$Frequency), collapse = ", ")))
kbl(dat_input_params, 
    col.names = NULL) %>%
  kable_styling(full_width = F,
                position = "left",
                font_size = 16)
```


### Summary

```{r, echo=FALSE}
library(kableExtra)
dat_summary <- data.frame(stat = c("Total Surveys",
                                   "Current Surveys",
                                   "Surveys with Protocols",
                                   "Inventory Surveys",
                                   "Monitoring Surveys",
                                   "Research"),
                          value = c(nrow(input_dat),
                                    input_dat %>% filter(SurveyStatus == "Current") %>% nrow(),
                                    paste0(input_dat %>% filter(HasProtocol == "Has Protocol") %>% nrow(), " (", round(input_dat %>% filter(HasProtocol != "Has Protocol") %>% nrow() / input_dat %>% filter(SurveyStatus == "Current") %>% nrow(), digits = 0), "%)"),
                                    input_dat %>% filter(SurveyTypeShort == "Inventory") %>% nrow(),
                                    input_dat %>% filter(SurveyTypeShort == "Monitoring") %>% nrow(),
                                    input_dat %>% filter(SurveyTypeShort == "Research") %>% nrow())
                          )

kbl(dat_summary, 
    col.names = NULL) %>%
  kable_styling(full_width = F,
                position = "left",
                font_size = 16)
```


```{r tbl_DT, echo=FALSE, message=FALSE, warning=FALSE}
# library(DT)
# dat() %>%
#   dplyr::select(ProtocolTitle,
#                 StationName,
#                 SurveyName) %>%
#   dplyr::filter(ProtocolTitle != "NA") %>%
#   dplyr::arrange(ProtocolTitle, StationName, SurveyName) %>%
#   DT::datatable(caption = "Survey protocols for refuge surveys",
#                 colnames = c("Protocol",
#                              "Refuge",
#                              "Survey")
#   )
```


```{r tbl_protocols, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
library(flextable)
#set_flextable_defaults(fonts_ignore=TRUE)

if (nrow(dat()[dat()$ProtocolTitle == "NA", ]) == nrow(dat())) {
  cat("No protocols to display within your search criteria.")
} else {
  dat() %>%
    dplyr::select(ProtocolTitle,
                  StationName,
                  SurveyName) %>%
    dplyr::filter(ProtocolTitle != "NA") %>%
    dplyr::arrange(ProtocolTitle, StationName, SurveyName) %>%
    flextable::as_grouped_data(groups = c("ProtocolTitle")) %>%
    flextable::flextable() %>%
    set_header_labels(ProtocolTitle = "Protocol",
                      StationName = "Refuge",
                      SurveyName = "Survey") %>%
    width(j = ~ProtocolTitle, width = 3) %>%
    width(j = ~StationName, width = 1) %>%
    width(j = ~SurveyName, width = 3) %>%
    set_caption(paste("Survey protocols for Refuges in the", unique(dat()$RegionName), "Region."))
} 
```

\newpage


```{r tbl_surveys, echo=FALSE, message=FALSE, warning=FALSE, fig.cap= "Refuge surveys in Alaska."}
set_flextable_defaults(fonts_ignore=TRUE)
dat() %>%
  dplyr::select(StationName, SurveyName, SurveyStatus, Selected) %>%
  dplyr::arrange(StationName, SurveyName, SurveyStatus, Selected) %>%
  flextable::as_grouped_data(groups = c("StationName")) %>%
  flextable::flextable() %>%
  flextable::set_header_labels(StationName = "Refuge",
                    SurveyName = "Survey",
                    SurveyStatus = "Status",
                    Selected = "Selected?") %>%
  flextable::autofit() %>%
  width(j = ~StationName, width = 1) %>%
  width(j = ~SurveyName, width = 2.75) %>%
  width(j = ~SurveyStatus, width = 2.75) %>%
  width(j = ~Selected, width = 0.5) %>%
  set_caption(paste("Refuge surveys in the", unique(dat()$RegionName), "Region."))

```

